// Legacy single-study key, kept only so existing saved progress can be
// migrated into the first study the first time useStudies.js loads.
export const STORAGE_KEY = "transpetro-study-data-v1";
export const STUDIES_KEY = "study-tracker-studies-v1";
export const POMODORO_KEY = "transpetro-pomodoro-v1";
export const EXAM_DATE = new Date("2026-11-29T13:00:00-03:00");
export const WORK_SECONDS = 25 * 60;
export const BREAK_SECONDS = 5 * 60;
export const SUBJECT_COLORS = ["#2E8C90", "#F2A93B", "#6FA96C", "#D9643A"];

export const DEFAULT_SUBJECTS = [
  {
    id: "portugues",
    name: "Língua Portuguesa",
    color: "#2E8C90",
    topics: [
      { id: "p1", text: "Compreensão de textos", done: false },
      { id: "p1a", text: "Tipos de texto (narrativo, dissertativo, descritivo)", done: false },
      { id: "p1b", text: "Interpretação implícita e explícita", done: false },
      { id: "p2", text: "Ortografia oficial", done: false },
      { id: "p2a", text: "Acordo ortográfico vigente", done: false },
      { id: "p2b", text: "Uso do hífen e acentuação gráfica", done: false },
      { id: "p3", text: "Mecanismos de coesão textual", done: false },
      { id: "p3a", text: "Coesão referencial e sequencial", done: false },
      { id: "p3b", text: "Uso de conectivos", done: false },
      { id: "p4", text: "Significação das palavras", done: false },
      { id: "p4a", text: "Sinonímia, antonímia e polissemia", done: false },
      { id: "p4b", text: "Denotação e conotação", done: false },
      { id: "p5", text: "Emprego de tempos e modos verbais", done: false },
      { id: "p5a", text: "Modo indicativo, subjuntivo e imperativo", done: false },
      { id: "p5b", text: "Tempos compostos", done: false },
      { id: "p6", text: "Emprego das classes de palavras", done: false },
      { id: "p6a", text: "Substantivo, adjetivo e pronome", done: false },
      { id: "p6b", text: "Verbo, advérbio, preposição e conjunção", done: false },
      { id: "p7", text: "Coordenação e subordinação", done: false },
      { id: "p7a", text: "Orações coordenadas (sindéticas e assindéticas)", done: false },
      { id: "p7b", text: "Orações subordinadas (substantivas, adjetivas, adverbiais)", done: false },
      { id: "p8", text: "Emprego dos sinais de pontuação", done: false },
      { id: "p8a", text: "Vírgula, ponto e vírgula e dois-pontos", done: false },
      { id: "p8b", text: "Uso do travessão", done: false },
      { id: "p9", text: "Concordância verbal e nominal", done: false },
      { id: "p9a", text: "Casos particulares de concordância verbal", done: false },
      { id: "p9b", text: "Casos particulares de concordância nominal", done: false },
      { id: "p10", text: "Regência verbal e nominal", done: false },
      { id: "p10a", text: "Regência de verbos comuns em provas", done: false },
      { id: "p10b", text: "Regência nominal", done: false },
      { id: "p11", text: "Emprego do sinal indicativo de crase", done: false },
      { id: "p11a", text: "Regras gerais de crase", done: false },
      { id: "p11b", text: "Casos facultativos e proibidos", done: false },
      { id: "p12", text: "Colocação dos pronomes átonos", done: false },
      { id: "p12a", text: "Próclise, mesóclise e ênclise", done: false },
    ],
  },
  {
    id: "ingles",
    name: "Língua Inglesa",
    color: "#2E8C90",
    topics: [
      { id: "i1", text: "Compreensão de texto escrito", done: false },
      { id: "i1a", text: "Leitura técnica (tecnologia, logística, petróleo, navegação)", done: false },
      { id: "i1b", text: "Vocabulário técnico e cognatos", done: false },
      { id: "i2", text: "Itens gramaticais relevantes", done: false },
      { id: "i2a", text: "Tempos verbais (verb tenses)", done: false },
      { id: "i2b", text: "Verbos modais (modal verbs)", done: false },
      { id: "i2c", text: "Phrasal verbs", done: false },
      { id: "i2d", text: "Discurso direto e indireto", done: false },
      { id: "i2e", text: "Conjunções e preposições", done: false },
      { id: "i2f", text: "Voz passiva", done: false },
      { id: "i2g", text: "Orações condicionais", done: false },
      { id: "i2h", text: "Afixação (prefixos e sufixos)", done: false },
    ],
  },
  {
    id: "processos",
    name: "Processos de Negócio",
    color: "#F2A93B",
    topics: [
      { id: "n1", text: "Arquitetura de Dados (modelagem, SQL, NoSQL, ETL)", done: false },
      { id: "n1a", text: "Modelagem de dados (conceitual, lógica, física)", done: false },
      { id: "n1b", text: "SQL (DDL, DML, DQL)", done: false },
      { id: "n1c", text: "Bancos NoSQL", done: false },
      { id: "n1d", text: "Processos de ETL", done: false },
      { id: "n2", text: "Gerenciamento de Projetos (Scrum, Kanban, PMBOK, SAFe)", done: false },
      { id: "n2a", text: "Scrum", done: false },
      { id: "n2b", text: "Kanban", done: false },
      { id: "n2c", text: "PMBOK (grupos e áreas de conhecimento)", done: false },
      { id: "n2d", text: "SAFe (ágil em escala)", done: false },
      { id: "n3", text: "Processos (grupos e áreas de conhecimento PMBOK)", done: false },
      { id: "n3a", text: "5 grupos de processos", done: false },
      { id: "n3b", text: "10 áreas de conhecimento", done: false },
      { id: "n4", text: "Gestão e Governança em TI / LGPD", done: false },
      { id: "n4a", text: "Governança de TI (COBIT/ITIL)", done: false },
      { id: "n4b", text: "Gestão de serviços de TI", done: false },
      { id: "n4c", text: "LGPD", done: false },
      { id: "n5", text: "Engenharia de Software (requisitos, ciclo de vida)", done: false },
      { id: "n5a", text: "Levantamento e gestão de requisitos", done: false },
      { id: "n5b", text: "Ciclo de vida de sistemas", done: false },
      { id: "n5c", text: "Metodologias estruturada e orientada a objetos", done: false },
      { id: "n6", text: "UX (usabilidade, design thinking, MVP, personas)", done: false },
      { id: "n6a", text: "Usabilidade e acessibilidade", done: false },
      { id: "n6b", text: "Design thinking e prototipação", done: false },
      { id: "n6c", text: "MVP e personas", done: false },
      { id: "n7", text: "Análise de Dados e BI (DW, OLAP, dashboards)", done: false },
      { id: "n7a", text: "Data Warehouse", done: false },
      { id: "n7b", text: "OLAP", done: false },
      { id: "n7c", text: "Dashboards e storytelling com dados", done: false },
      { id: "n8", text: "Lógica Matemática (sentencial, predicados)", done: false },
      { id: "n8a", text: "Lógica sentencial e tabelas-verdade", done: false },
      { id: "n8b", text: "Lógica de predicados", done: false },
      { id: "n9", text: "Segurança da Informação (visão geral)", done: false },
      { id: "n9a", text: "Firewall, IDS/IPS e malwares", done: false },
      { id: "n9b", text: "Criptografia e ISO 27002", done: false },
      { id: "n9c", text: "Gestão de riscos (ISO 31000) e LGPD", done: false },
    ],
  },
];
